### PR TITLE
fix: do not reference undefined google during component mounting

### LINKED ISSUE #219: Unhandled Exception Google is not Defined
**Describe the bug** A clear and concise description of what the bug is.
The issue im seeing is when the google pay script doesnt load, an unhandled exception is thrown instead of passing the error to the `config.onError`.

**To Reproduce** Steps to reproduce the behavior:

1. Go to [this stackblitz](https://stackblitz.com/edit/google-pay-angular?file=package.json)
2. Click on update all dependencies to latest
3. inspect the page and block `https://pay.google.com/gp/p/`

**Expected behavior** A clear and concise description of what you expected to happen.
The `updateElement` function should have a check that google is defined before invoking `this.client = new google.payments.api.PaymentsClient(this.createClientOptions(this.config));`

**Screenshots** If applicable, add screenshots to help explain your problem.
Screenshot 2023-04-19 at 10 05 35 AM

**Component information:**

- Component
  - [ ] React component (`@google-pay/button-react`)
  - [ ] Custom element (`@google-pay/button-element`)
  - [x] Angular component (`@google-pay/button-angular`)
- Component version (e.g. 1.0.0):

**Environment:**

- Device (e.g. iPhone6):
- OS (e.g. iOS8.1):
- Browser (e.g. stock browser, safari)
- Country/region:

**Additional context** Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by dmengelt**
Without returning from the `mount()` function if there was an error loading `pay.js` we continue to call `this.updateElement();` this will result in trying to reference the undefined `google` object:

https://github.com/google-pay/google-pay-button/blob/812855408177dfa7a022849566bdd298ed477231/src/lib/button-manager.ts#L231

fixes #219

### CODE REVIEW

**Comment by JlUgia** [comment]
LGTM
FYI @socsieng

**Review by JlUgia — APPROVED** [review]

File: src/lib/button-manager.ts [hunk 1]
```diff
@@ -86,6 +86,7 @@ export class ButtonManager {
           console.error(err);
         }
       }
+      return;
```
Comment (amakhrov) [inline src/lib/button-manager.ts:89]: it returns regardless on whether `await loadScript('https://pay.google.com/gp/p/js/pay.js');` succeeded or failed.
is it intentional? should the `return` be moved inside the `catch (err) {...}` block instead?

Comment (amakhrov) [reply src/lib/button-manager.ts:89]: nvm, I see it was address in a followup PR! sorry :)
